server {
	listen 80 default_server;
	listen [::]:80 default_server;

    index index.php index.html;
    client_max_body_size 100M;
    root /var/www/html/public;

    server_name _;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    error_page 404 /404.json;
    error_page 413 /413.json;
    error_page 504 /504.json;

    location = /404.json {
        return 200 '{"message": "Recurso não encontrado"}';
        add_header Content-Type application/json;
    }

    location = /413.json {
        return 200 '{"message": "Requesição excedeu o tamanho do payload permitido"}';
        add_header Content-Type application/json;
    }

    location = /504.json {
        return 200 '{"message": "A requisição falhou. Atualize a página e tente novamente"}';
        add_header Content-Type application/json;
    }

    location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include fastcgi_params;
        }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
